pipeline {
    agent any
    stages {                 
        stage('prepare code') {
            steps {
                
                sh "mvn -P ${params.env} process-resources"
            
            }
        }
        stage('Deploy Kvms, Caches and Target servers') {
            
            steps {
                withCredentials([usernamePassword(credentialsId: 'Dana_Apigee_Cred', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                sh '''
                string="${env.PRE_PROXY_DEPLOYMENT_CONFIG}"
                if [[ $string == "kvms" ]]; then
f               
                elif [[ $string == "targetservers" ]]; then                
                elif [[ $string == "caches" ]]; then
                mvn -P ${params.env} -Dapigee.config.dir=./target/edge -Da.username=${USERNAME} -Da.password=${PASSWORD} -Dapigee.config.options=update apigee-config:caches
                
                else 
                echo "No configs selected"

                fi
                '''
                }
            }
        }
        
		stage('Deploy proxy and Api Products') {
            when {
            expression {$PROXY_DEPLOYMENT == 'true'}
        }
            steps {
            	withCredentials([usernamePassword(credentialsId: 'Dana_Apigee_Cred', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                sh "mvn -P ${params.env} -Dapigee.config.dir=./target/edge -Da.username=${USERNAME} -Da.password=${PASSWORD} -Dapigee.config.options=none deploy"
            }
        }
        }
    }   
   
}
